### ISSUE TITLE
Единообразие в стиле кода — показатель уровня разработчика

### ISSUE THREAD

**Issue by phoenixweiss** [MeldyTheCoder/homework_4#1]
Сущая мелочь, но всё же:
https://github.com/MeldyTheCoder/homework_4/blob/0c2bcea318a67eaa23ea4ec82b41f13c9ce97fd4/script.js#L11-L12
Для JS безразлично, это 1.0 и 0.0 или 1 и 0. Но лучше просто придерживаться одного типа при использовании хотя бы чисто визуально.
Кроме того здесь же и по всем строкам где-то есть `;` а где-то нет. Если пишете современный ES6-совместимый код для которого `;` не требуются — не вопрос, тогда нигде не используйте, а если используете — то везде. Чисто стилистически это часто показывает уровень аккуратности.
Вообще здорово что сделали за 10 минут, но в программировании часто внимательность и аккуратность важнее скорости, если только речь не про спортивное или олимпиадное программирование.

**Comment by MeldyTheCoder** [comment]
Исправил
